import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import Header from "../_components/Header";
import useTextDirection from "../_hooks/useTextDirection";
import "./globals.css";
import { NextIntlClientProvider, useMessages } from "next-intl";
import arMessages from "../../locales/ar.json";
import enMessages from "../../locales/ar.json";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],
});

export default function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  // unstable_setRequestLocale(locale);
  const dir = useTextDirection();
  const messages = useMessages();
  return (
    <html lang={locale} dir={dir}>
      <body className={roboto.className}>
        <NextIntlClientProvider messages={messages}>
          <Header />
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
