import type { Metadata } from "next";
import Header from "../_components/Header";
import useTextDirection from "../_hooks/useTextDirection";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  const dir = useTextDirection();

  return (
    <html lang={locale} dir={dir}>
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
